#Se especifican rutas para no verificar todo el contenido y se trabaja con una version especifica.
FROM maven:3.6.3-jdk-14 as app
COPY words /app
WORKDIR /app 
RUN mvn verify

FROM openjdk:11-jre-alpine
WORKDIR /home/app 
COPY --from=app /app/target ./target

CMD [ "java","-Xmx8m", "-Xms8m", "-jar", "/build/target/words.jar" ]
EXPOSE 8080