#Solo use && para concatenar las instrucciones en los Run
#y la multi etapa  la deje una para compilar y
#y un sistemas mas liviano para ejecutarlo

FROM golang:latest as builder

WORKDIR /app
COPY dispatcher.go .
RUN go mod init main && go build -o /dispatcher

FROM alpine
WORKDIR /home/builder
COPY --from=builder . .
CMD [ "/dispatcher" ]